{{- with .Values.serviceMonitor }}
{{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: {{- include "common.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
  name: {{ include "common.names.fullname" . }}
spec:
  endpoints:
    - interval: 5m
      port: http
      scrapeTimeout: 1m
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
{{- end }}
