# Inspired by https://github.com/bitnami/charts
# Utilizes https://github.com/bitnami/charts/tree/main/bitnami/common

global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

nameOverride: ""
fullnameOverride: ""

image:
  registry: ghcr.io
  repository: mikaelelkiaer/checkupdates-prometheus-exporter
  tag: 1.0.7
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
