name: Create Cluster

on:
  push:
    branches:
      - main
    paths:
      - helm/**
    tags:
      - "helm-v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - helm/**

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Test - lint
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      - name: Create Kind cluster
        uses: helm/kind-action@v1.5.0
      - name: Test - install
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
